/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _HW_H_RPCGEN
#define _HW_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


#define HELLO_WOLRD_PROG 0x30000824
#define HELLO_WORLD_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define HW 1
extern  char ** hw_1(void *, CLIENT *);
extern  char ** hw_1_svc(void *, struct svc_req *);
#define GETCHAT 2
extern  char ** getchat_1(int *, CLIENT *);
extern  char ** getchat_1_svc(int *, struct svc_req *);
#define PUTCHAT 3
extern  void * putchat_1(char **, CLIENT *);
extern  void * putchat_1_svc(char **, struct svc_req *);
extern int hello_wolrd_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define HW 1
extern  char ** hw_1();
extern  char ** hw_1_svc();
#define GETCHAT 2
extern  char ** getchat_1();
extern  char ** getchat_1_svc();
#define PUTCHAT 3
extern  void * putchat_1();
extern  void * putchat_1_svc();
extern int hello_wolrd_prog_1_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_HW_H_RPCGEN */
